export const APP_CONFIG = {
  name: 'PRINTLAB 3D',
  tagline: 'Modern 3D Printing Showcase & Instant UPI Ordering',
  description: 'Modern Gen-Z 3D Printing Showcase & Instant UPI Ordering with dynamic time-based day/night themes, KPR campus delivery, and 6-stage order tracking.',
  upiId: 'sanjay150724@okaxis',
  merchantName: 'PRINTLAB 3D Studio',
  currency: 'INR',
  currencySymbol: '₹',
  supportEmail: 'support@printlab.io',
  supportPhone: '+91 9894709708',
} as const;

export const KPR_COLLEGE_CONFIG = {
  name: 'KPR Institute of Engineering and Technology',
  city: 'Coimbatore',
  state: 'Tamil Nadu',
  pincode: '641407',
  departments: [
    'Computer Science & Engineering (CSE)',
    'Artificial Intelligence & Data Science (AI & DS)',
    'Information Technology (IT)',
    'Electronics & Communication Engineering (ECE)',
    'Mechanical Engineering (MECH)',
    'Civil Engineering (CIVIL)',
    'Electrical & Electronics Engineering (EEE)',
    'Biomedical Engineering (BME)',
    'Chemical Engineering',
    'Mechatronics Engineering',
    'MBA / Management',
    'Other / Faculty / Staff',
  ],
  blocks: [
    'Main Academic Block',
    'Thillai Block',
    'Veena Block',
    'Mechanical & Civil Workshop Block',
    'Central Library & Innovation Lab',
    'Boys Hostel Block A / B / C',
    'Girls Hostel Block',
    'Campus Cafeteria & Food Court',
  ],
  pickupLocations: [
    'Classroom Delivery',
    'Department Staff Room',
    'Hostel Room Delivery',
    'Campus Gate 1 Pickup',
    'Campus Gate 2 Pickup',
    'Innovation Lab / Maker Space',
  ],
} as const;
