export const ROUTES = {
  HOME: '/',
  PRODUCTS: '/products',
  PRODUCT_DETAILS: '/products/:slug',
  ORDER: '/order',
  CHECKOUT: '/checkout',
  PAYMENT: '/payment',
  PAYMENT_ORDER: '/payment/:orderId',
  PAYMENT_VERIFICATION: '/payment-verification',
  ORDER_SUCCESS: '/order-success/:id',
  ORDER_SUCCESS_GENERIC: '/order-success',
  TRACK: '/track',
  ABOUT: '/about',
  LOGIN: '/login',
  CUSTOMER_LOGIN: '/customer/login',
  CUSTOMER_ORDERS: '/customer/orders',
  CUSTOMER_DASHBOARD: '/customer/dashboard',
  ADMIN_LOGIN: '/admin/login',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_ORDERS: '/admin/orders',
  ADMIN_PRODUCTS: '/admin/products',
  ADMIN_SETTINGS: '/admin/settings',
} as const;
